# Copyright 2023 Salesforce, Inc. All rights reserved.
version: "3.3"

services:
  local-flex:
    image: mulesoft/flex-gateway:1.7.1
    ports:
      - 8081:8081
    volumes:
      - ./config:/usr/local/share/mulesoft/flex-gateway/conf.d/
  backend:
    image: kennethreitz/httpbin
  proxy-https: # Facade to interact with the backend using custom tls configuration.
    image: fsouza/docker-ssl-proxy
    environment:
      TARGET_HOST: backend
    links:
      - backend
    volumes:
      - ./certs:/etc/nginx/certs
