# Copyright 2023 Salesforce, Inc. All rights reserved.
version: "3.3"

services:
  local-flex:
    image: artifacts.msap.io/mulesoft/microgateway:v1.10.1.26e83c4
    ports:
      - 8081:8081
    volumes:
      - ./config:/usr/local/share/mulesoft/flex-gateway/conf.d/
  backend:
    image: kennethreitz/httpbin

  # A gripmock server is configured by default with predefined authentication stubs.
  gripmock:
    image: tkpd/gripmock:v1.13
    volumes:
      - ../proto:/proto
      - ./stub:/stub
    command: --stub=/stub /proto/auth.proto

