# Copyright 2023 Salesforce, Inc. All rights reserved.
version: "3.3"

services:
  local-flex:
    image: mulesoft/flex-gateway:1.6.2
    ports:
      - 8081:8081
    volumes:
      - ./config:/usr/local/share/mulesoft/flex-gateway/conf.d/
  backend:
    image: kennethreitz/httpbin
  oauth-server:
    image: colinodell/static-response-server
    environment:
      - "HTTP_CODE=200"
      - 'HTTP_BODY={"active":true}'
      - "HTTP_HEADERS=Content-Type: application/json"
