[registry]
global-credential-providers = ["cargo:token"]

[registries]
anypoint = { index = "https://stgx.anypoint.mulesoft.com/git/68ef9520-24e9-4cf2-b2f5-620025690913/e8cb2611-8681-4ec5-af55-6b5b812a86fa" }

[net]
git-fetch-with-cli = true
