---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: A2A PII Detector
    description: Detects sensitive data sent to or from an agent.
    category: A2A
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    action:
      title: Action
      type: string
      description: Action to take if sensitive data is found. A policy violation is always reported.
      default: Reject
      enum:
        - Reject
        - Log
  required:
    - action