---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: "Simple gRPC OAuth 2.0 Validation Policy"
    description: "Validates incoming tokens against an gRPC auth service"
    category: Security
spec:
  extends:
    - name: extension-definition
  properties:
    authorization:
      type: string
      description: "Authorization header to authenticate against the external auth server"
    oauthService:
      type: string
      format: service
    tokenExtractor:
      type: string
      format: dataweave
      default: "#[dw::core::Strings::substringAfter(attributes.headers['Authorization'], 'Bearer ')]"
  required:
    - authorization
    - oauthService
    - tokenExtractor
