[registry]
global-credential-providers = ["cargo:token"]

[registries]
anypoint = { index = "https://qax.anypoint.mulesoft.com/git/68ef9520-24e9-4cf2-b2f5-620025690913/9be4ef3a-cb3e-479c-a1c4-e47cf2e02540" }

[net]
git-fetch-with-cli = true
