---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: "Multi-Instance Rate Limiting"
    description: "Simple rate limiting policy that supports multiple configurations and can be shared across multiple gateway instances using rate-limit-lib with Redis support"
    category: Custom
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    rate_limits:
      type: array
      description: Array of rate limit configurations. All configurations will be applied to each request. A request must pass all rate limits to be allowed.
      items:
        type: object
        properties:
          group_name:
            type: string
            description: Name of the rate limit group (e.g., 'api', 'user', 'premium'). Each group operates independently.
          requests_per_window:
            type: integer
            description: Maximum number of requests allowed in the time window
            minimum: 1
          window_size_seconds:
            type: integer
            description: Time window size in seconds
            minimum: 1
          key_selector:
            type: string
            enum: [api_key, user_id]
            description: How to identify the client for rate limiting. 'api_key' uses x-api-key header, 'user_id' uses x-user-id header
        required:
          - group_name
          - requests_per_window
          - window_size_seconds
          - key_selector
  
  required:
    - rate_limits
