---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: "Simple Multi-Instance Rate Limiting"
    description: "Simple rate limiting policy that can be shared across multiple gateway instances using rate-limit-lib"
    category: Custom
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    rate_limits:
      type: array
      description: Array of rate limit configurations (only the first one will be used)
      items:
        type: object
        properties:
          group_name:
            type: string
            description: Name of the rate limit group (e.g., 'api', 'auth', 'premium')
          requests_per_window:
            type: integer
            description: Maximum number of requests allowed in the time window
            minimum: 1
          window_size_seconds:
            type: integer
            description: Time window size in seconds
            minimum: 1
          key_selector:
            type: string
            enum: [api_key, user_id]
            description: How to identify the client for rate limiting
        required:
          - group_name
          - requests_per_window
          - window_size_seconds
          - key_selector
  
  required:
    - rate_limits
