# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: ai-prompt-template-v1-0-impl # This value will be overriden during 'make run' execution
        namespace: default
      config:
        templates:
          - name: veterinarian-chat
            template: |-
              {
                "messages": [
                  {
                    "role": "system",
                    "content": "You are a {{system}} expert, in {{species}} species."
                  },
                  {
                    "role": "user",
                    "content": "Describe me the {{system}} system."
                  }
                ]
              }
