# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: simple-oauth-2-validation-v1-0-impl
        namespace: default
      config:
        # If you want to use the Oauth Service mock defined in docker-compose.
        # yaml, use `http://oauth-server:8080` for `oauthService` value. If
        # you created a local mock in your host, listening at port 5001, use
        # `http://host.docker.internal:5001`
        oauthService: http://oauth-server:8080
        # The authorization is for introspection service
        # The Oauth Service mock defined in docker-compose.yaml ignores it
        authorization: whatever
