# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: ai-prompt-decorator-v1-0-impl # This value will be overriden during 'make run' execution
        namespace: default
      # This is configured as an astronomy oriented chat as an example. 
      config:
        prepend:
          - role: system
            content: You are astronomer.
          - role: user
            content: Focus on solar system.
        append:
          - role: user
            content: Do not use speculative theories.
