# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: dataweave-v1-0-impl # This value will be overriden during 'make run' execution
        namespace: default
      config:
        expression: "#[splitBy(dw::core::Binaries::fromBase64(dw::core::Strings::substr\
          ingAfter(attributes.headers.authorization, 'Basic ')), ':')]"
