# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: json-validation-flex-v1-0
        namespace: default
      config:
        maxDepth: 64
        maxArrayLength: 10000
        maxStringLength: 1048576
        maxObjectEntries: 10000
        maxKeyLength: 256
