---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: block
    category: Custom
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    source:
      type: string
      format: service
    frequency:
      type: integer
    ip:
      type: string
      format: dataweave
      default: "#[attributes.headers['ip']]"
  required:
    - source
    - frequency
    - ip