---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: "Data Caching Policy"
    category: Custom
spec:
  extends:
    - name: extension-definition
  properties:
    max_cached_values:
      type: integer
      default: 100
    start_hour:
      type: integer
      default: 18
    end_hour:
      type: integer
      default: 10
  required:
    - max_cached_values
    - start_hour
    - end_hour