---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: "Simple OAuth 2.0 Validation Policy"
    category: Custom
spec:
  extends:
    - name: extension-definition
  properties:
    authorization:
      type: string
    oauthService:
      type: string
      format: service
    tokenExtractor:
      type: string
      format: dataweave
      default: "#[dw::core::Strings::substringAfter(attributes.headers['Authorization'], 'Bearer ')]"
  required:
    - authorization
    - oauthService
    - tokenExtractor
