# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: ai-basic-token-rate-limiting-v1-0-impl # This value will be overriden during 'make run' execution
        namespace: default
      config:
        maximumTokens: 15
        timePeriodInMilliseconds: 10000
