# Copyright 2023 Salesforce, Inc. All rights reserved.
version: "3.3"

services:
  local-flex:
    image: artifacts.msap.io/mulesoft/microgateway:v1.10.1.26e83c4
    ports:
      - 8081:8081
    volumes:
      - ./config:/usr/local/share/mulesoft/flex-gateway/conf.d/
  backend:
    image: kennethreitz/httpbin
  oauth-server:
    image: colinodell/static-response-server
  block-server:
      image: colinodell/static-response-server
      environment:
        - "HTTP_CODE=200"
        - 'HTTP_BODY=24.152.57.0/24'
        - "HTTP_HEADERS=Content-Type: application/text"